#!/bin/bash

# apps
sxhkd -c $HOME/.config/berry/sxhkdrc &
~/.config/autostart &

# berry
# set decoration geometry
berryc border_width       32
berryc inner_border_width 0
berryc title_height       0
berryc top_gap 		  30
berryc move_step	  30
berryc resize_step        30

# set decoration colors
berryc focus_color         000000
berryc unfocus_color       000000
berryc inner_focus_color   ffffff
berryc inner_unfocus_color ffffff
berryc text_focus_color    000000
berryc text_unfocus_color  000000

# other options
berryc smart_place "false"
berryc draw_text   "false"
berryc edge_lock   "true"
berryc set_font    "Dina-10"

# desktops
for i in $(seq 0 2)
do
	berryc name_desktop $i $(expr $i + 1)
done
