#!/bin/bash

berryc border_width       0
berryc inner_border_width 0
berryc title_height       32
berryc top_gap            30
berryc move_step	  30
berryc resize_step	  30

berryc inner_focus_color   000000
berryc inner_unfocus_color 000000
berryc focus_color         000000
berryc unfocus_color       000000

berryc text_focus_color    ffffff
berryc text_unfocus_color  ffffff

berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "DroidSans-Mono-12"

for i in $(seq 0 2)
do
	berryc name_desktop $i $(expr $i + 1)
done

col_id=$(expr $RANDOM % 11)
col=gray
case $col_id in
  0) col=gray ;;
  1) col=dimgray ;;
  2) col=gainsboro ;;
  3) col=lightskyblue ;;
  4) col=lightslategray ;;
  5) col=lightsteelblue;;
  6) col=pink ;;
  7) col=salmon ;;
  8) col=tomato ;;
  9) col=palevioletred ;;
  10) col=turquoise ;;
  11) col=thistle ;;
esac
xsetroot -solid $col
