#!/bin/bash

berryc border_width       0
berryc inner_border_width 0
berryc title_height       32
berryc top_gap            30
berryc move_step	  30
berryc resize_step	  30

berryc inner_focus_color   ffffff
berryc inner_unfocus_color ffffff
berryc focus_color         000000
berryc unfocus_color       000000

berryc text_focus_color    000000
berryc text_unfocus_color  000000

berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "DroidSans-Mono-12"

for i in $(seq 0 2)
do
	berryc name_desktop $i $(expr $i + 1)
done

xsetroot -solid gray
